DROP DATABASE IF EXISTS userSchema;
CREATE DATABASE userSchema;

USE userSchema;

 CREATE TABLE users(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(25) NOT NULL,
	password VARCHAR(255) NOT NULL
 );